name: Run Backend Tests
run-name: ${{github.actor}} is testing the backend
on:
  pull_request:
    types: [opened, reopened]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: node BackEnd/model_test.js
